name: Copy JAR to EC2-2

on:
  workflow_dispatch:  # This allows manual execution from GitHub UI

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
    - name: Add EC2-1 to Known Hosts
      env:
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

    - name: Retrieve JAR from EC2-1
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST:/home/$USER/app.jar app.jar

    - name: Add EC2-2 to Known Hosts
      env:
        HOST: ${{ secrets.EC2_2_HOST }}
      run: |
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

    - name: Transfer JAR to EC2-2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem app.jar $USER@$HOST:/home/$USER/app.jar

    - name: Restart Application on EC2-2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          sudo pkill -f 'java -jar' || true
          nohup java -jar /home/$USER/app.jar > /home/$USER/app.log 2>&1 &
          exit
        EOF
